version: '3'

services:

  #  todo-app:
  #    image: 'todo-app:latest'
  #    container_name: todo-app
  #    ports:
  #      - "8081:8081"
  #    depends_on:
  #      - todo-app-db
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://todo-app-db:5432/custom_database
  #      - SPRING_DATASOURCE_USERNAME=postgres
  #      - SPRING_DATASOURCE_PASSWORD=password
  #      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #      - KEYCLOAK=todo-app-keycloak-svc


  todo-app-db:
    image: 'postgres:13.1-alpine'
    container_name: test-app-db-cont
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=custom_database
    ports:
      - "32032:5432"